python/ziqiangxuetang/zqxt_form_ajax/zqxt_form_ajax/urls.py
from django.conf.urls import url
from django.contrib import admin
from tools import views

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url('^index/$', views.index, name='add'),
    url('^add/$', views.add, name='add'),
    url(r'^admin/', admin.site.urls),
]

python/ziqiangxuetang/zqxt_form_ajax/tools/models.py
from django.db import models

# Create your models here.

python/ziqiangxuetang/zqxt_form_ajax/tools/forms.py
#!/usr/bin/env python
# encoding: utf-8
"""
@version: Python 3.52
@author: Uxeix
@license: Apache Licence 
@contact: uxeixs@gmail.com
@site: https://github.com/uxiexs
@software: PyCharm
@file: forms.py
@time: 2016/9/27 16:38
"""
from django import forms

class AddForm(forms.Form):
    a = forms.IntegerField()
    b = forms.IntegerField()

python/ziqiangxuetang/zqxt_form_ajax/tools/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import AddForm


# Create your views here.
def index(request):
    form = AddForm()
    return render(request,'tools/index.html', {'forms': form})

def add(request):
    a = request.GET['a']
    b = request.GET['b']
    return HttpResponse(str(int(a) + int(b)))

python/ziqiangxuetang/zqxt_form_ajax/tools/templates/tools/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}默认标题{% endblock %}</title>
</head>
<body>
{% block content %}

{% endblock %}
</body>
</html>

python/ziqiangxuetang/zqxt_form_ajax/tools/templates/tools/index.html
{% extends 'tools/base.html'%}

<!--title-->
{% block title %}Django Ajax {% endblock %}

<!--content-->
{% block content %}
<p>请输入两个数字</p>
{% csrf_token %}
<form action="/add/" method="POST">
    <!--a: <input type="text" id="a" name="a"> <br>-->
    <!--b: <input type="text" id="b" name="b"> <br>-->
    {% for field in forms %}
    <div class='fieldWrapper' style="padding: 10px">
        {{field.label_tag}} {{field}}
        {{field.errors}}
    </div>
    {% endfor %}
    <p>result: <span id="result"></span></p>
    <button type="button" id="sum">提交</button>
</form>

<script src="http://apps.bdimg.com/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#sum").click(function () {
            var a = $("#id_a").val();
            var b = $("#id_b").val();

            $.get("/add/", {'a': a, 'b': b}, function (ret) {
                $("#result").html(ret)
            })
        })
    })
</script>

{% endblock %}